version: "3.7"

services:

  flask:
    build: ./app
    container_name: app
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:80"