apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: trevdev0/flask-app:latest
          ports:
            - containerPort: 5000
              name: flask-uwsgi
---
apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      name: flask
  selector:
    app: flask-app