apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-nginx
  labels:
    app: flask-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-nginx
  template:
    metadata:
      labels:
        app: flask-nginx
    spec:
      containers:
      - name: flask-nginx
        image: trevdev0/flask-nginx:latest 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask-nginx-svc
spec:
  selector:
    app: flask-nginx
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
